version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Set replication factor to 1 for __consumer_offsets
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # Set replication factor to 1 for transaction logs
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1  # Set min in-sync replicas for transaction logs

